name: Static Check

on:
  pull_request:
    branches: [ master ]

jobs:
  static_check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Prepare Environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y buildah

    - name: Run The Test
      run: ./tests/static-check/run.sh
