name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  nodeps_unit_tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y autoconf automake gcc
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug --with-pcre2=no --with-openssl=no --with-libyaml=no
    - name: Compile and link (make)
      run: make CFLAGS="-Werror -Wall"
    - name: Run unit tests
      run: make check

  unit_tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y autoconf automake gcc libssl-dev libpcre2-dev libyaml-dev
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link (make)
      run: make CFLAGS="-Wall -Wextra -Werror -Wno-sign-compare"
    - name: Run unit tests
      run: make -C tests/unit check
